### ISSUE TITLE
Unable to start Tinker-FFE

### ISSUE THREAD

**Issue by Tenshi65535** [TinkerTools/tinker-ffe#1]
Hello,
I installed Tinker and Tinker-FFE but failed to start Tinker-FFE
The output of terminal is captured as below:

    com.jogamp.opengl.GLException: Not a GL2 implementation`
    	at jogamp.opengl.es1.GLES1Impl.getGL2(GLES1Impl.java:4929)`
    	at org.jogamp.java3d.JoglPipeline.createNewContext(JoglPipeline.java:6432)
    	at org.jogamp.java3d.Canvas3D.createNewContext(Canvas3D.java:4602)
    	at org.jogamp.java3d.Canvas3D.createNewContext(Canvas3D.java:2376)
    	at org.jogamp.java3d.Renderer.doWork(Renderer.java:881)
    	at org.jogamp.java3d.J3dThread.run(J3dThread.java:271)
    DefaultRenderingErrorListener.errorOccurred:
    CONTEXT_CREATION_ERROR: Renderer: Error creating Canvas3D graphics context
    graphicsDevice = X11GraphicsDevice[screen=0]
    canvas = 3D Graphics
    EGLDisplayUtil.EGLDisplays: Shutdown (open: 1)
    EGLDisplayUtil: Open EGL Display Connections: 1
    EGLDisplayUtil: Open[0]: 0x7f981001fd30: EGLDisplayRef[0x7f981001fd30: refCnt 1]
    X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open, marked uncloseable): 0, pending (open in creation order): 1)
    X11Util: Open X11 Display Connections: 1
    X11Util: Open[0]: NamedX11Display[:0.0, 0x7f9810038390, refCount 1, unCloseable false]

This is probably related to OpenGL but I have no idea how to fix this.

**Comment by jayponder** [comment]
Let me guess, you are using Ubuntu 20.04?

This is a known issue. For 20.04 an updated mesa OpenGL library needs to be packaged with FFE. I have this working on Ubuntu 20.04 and any distribution that needs the newer library. I assume you are trying to use the FFE from the install kit on the Ponder lab wet site? I've not yet posted new install kits on that site, but should be able to do so shortly. We have upgraded a bunch of internal stuff in FFE, and while I've solved exactly the Ubuntu 20.04 issue you describe, there is also a problem on Windows 10 that I want to track down and fix before posting new kits. It's always something...

If I'm wrong and you are not on Ubuntu 20.04, then please post more details of your system.

**Comment by Tenshi65535** [comment]
Thanks for your reply.

The system I'm using is Manjaro and the package is from Ponder lab website directly.
I guess it is caused by the same reason as the one in Ubuntu. I'll try the new kit and see if the problem still exists.

**Comment by jayponder** [comment]
As it may be a couple of weeks until new install kits are posted, in the meantime you could try this... I've put the library you need on my lab's server. Point a browser to:

https://dasher.wustl.edu/tinker/libEGL.so.1

That should download the library, which should be 276024 bytes. Put this library into the directory ~/Tinker-FFE/ffe/native/linux under your Tinker-FFE installation. No guarantees, but that might fix it. Let me know if that works.

**Comment by Tenshi65535** [comment]
After this library put into the directory FFE stuck at the initial image and gives the exception below

    java.lang.ExceptionInInitializerError
    	at org.jogamp.java3d.GraphicsConfigTemplate3D.getBestConfiguration(GraphicsConfigTemplate3D.java:317)
    	at java.awt.GraphicsDevice.getBestConfiguration(GraphicsDevice.java:207)
    	at ffe.core.MainPanel.initialize(MainPanel.java:829)
    	at ffe.Main.<init>(Main.java:165)
    	at ffe.Main.main(Main.java:119)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
    	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
    Caused by: com.jogamp.opengl.GLException: Profiles [GL4bc, GL3bc, GL2, GLES1] not available on device null
    	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1039)
    	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
    	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
    	at org.jogamp.java3d.JoglPipeline.initialize(JoglPipeline.java:135)
    	at org.jogamp.java3d.Pipeline.createPipeline(Pipeline.java:101)
    	at org.jogamp.java3d.MasterControl.loadLibraries(MasterControl.java:893)
    	at org.jogamp.java3d.VirtualUniverse.<clinit>(VirtualUniverse.java:267)
    	... 11 more

**Comment by jayponder** [comment]
OK. Thanks for testing that idea... I guess you will have to wait until I can post new installation kits. The new kits should fix the issue-- at least they do on Ubuntu 20.04, where the currently posted older kits give exactly the error in your original post. As mentioned above, it may be a couple of weeks until I get the new kits posted as "Tinker 8.8" at https://dasher.wustl.edu/tinker/.

Closing this for now. Once the new kits are available, let me know if they do not work correctly for you.
